# Generated by Django 3.2.10 on 2022-06-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_image_image_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile',
            new_name='image_profile',
        ),
    ]
