# Generated by Django 3.2.10 on 2022-06-06 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_profile_image_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
