# Generated by Django 3.2.10 on 2022-06-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220608_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_comments',
            field=models.TextField(),
        ),
    ]
